# Generated by Django 4.2.3 on 2023-08-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_carrera_alter_alumno_options_alter_profesor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrera',
            name='comision',
            field=models.IntegerField(),
        ),
    ]
