# Generated by Django 4.2.3 on 2023-09-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
